In [62]:
import pandas as pd

In [63]:
teams =[
  "diamondbacks",
  "braves",
  "orioles",
  "redsox",
  "cubs",
  "whitesox",
  "reds",
  "guardians",
  "rockies",
  "tigers",
  "astros",
  "royals",
  "angels",
  "dodgers",
  "marlins",
  "brewers",
  "twins",
  "mets",
  "yankees",
  "athletics",
  "phillies",
  "pirates",
  "padres",
  "giants",
  "mariners",
  "cardinals",
  "rays",
  "rangers",
  "bluejays",
  "nationals"
]

In [64]:
dataframes = {}

for i in teams:
    filepath = f'source/{i}.csv'
    dataframes[i] = pd.read_csv(filepath)
    dataframes[i]['team'] = i
    dataframes[i].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 30 non-null     float64
 1   Player             31 non-null     object
 2   Age                30 non-null     float64
 3   Pos                30 non-null     object
 4   WAR                31 non-null     float64
 5   G                  31 non-null     float64
 6   PA                 31 non-null     float64
 7   AB                 31 non-null     float64
 8   R                  31 non-null     float64
 9   H                  31 non-null     float64
 10  2B                 31 non-null     float64
 11  3B                 31 non-null     float64
 12  HR                 31 non-null     float64
 13  RBI                31 non-null     float64
 14  SB                 31 non-null     float64
 15  CS                 31 non-null     float64
 16  BB                 31 non-null     float64
 17  SO                 31 non-null     float64
 18  BA                 23 non-null     float64
 19  OBP                23 non-null     float64
 20  SLG                23 non-null     float64
 21  OPS                23 non-null     float64
 22  OPS+               23 non-null     float64
 23  rOBA               23 non-null     float64
 24  Rbat+              23 non-null     float64
 25  TB                 31 non-null     float64
 26  GIDP               31 non-null     float64
 27  HBP                31 non-null     float64
 28  SH                 31 non-null     float64
 29  SF                 31 non-null     float64
 30  IBB                31 non-null     float64
 31  Pos.1              30 non-null     object
 32  Awards             2 non-null      object
 33  Player-additional  32 non-null     object
 34  team               32 non-null     object
dtypes: float64(29), object(6)
memory usage: 8.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 27 non-null     float64
 1   Player             28 non-null     object
 2   Age                27 non-null     float64
 3   Pos                27 non-null     object
 4   WAR                28 non-null     float64
 5   G                  28 non-null     int64
 6   PA                 28 non-null     int64
 7   AB                 28 non-null     int64
 8   R                  28 non-null     int64
 9   H                  28 non-null     int64
 10  2B                 28 non-null     int64
 11  3B                 28 non-null     int64
 12  HR                 28 non-null     int64
 13  RBI                28 non-null     int64
 14  SB                 28 non-null     int64
 15  CS                 28 non-null     int64
 16  BB                 28 non-null     int64
 17  SO                 28 non-null     int64
 18  BA                 28 non-null     float64
 19  OBP                28 non-null     float64
 20  SLG                28 non-null     float64
 21  OPS                28 non-null     float64
 22  OPS+               28 non-null     int64
 23  rOBA               28 non-null     float64
 24  Rbat+              28 non-null     int64
 25  TB                 28 non-null     int64
 26  GIDP               28 non-null     int64
 27  HBP                28 non-null     int64
 28  SH                 28 non-null     int64
 29  SF                 28 non-null     int64
 30  IBB                28 non-null     int64
 31  Pos.1              27 non-null     object
 32  Awards             1 non-null      object
 33  Player-additional  28 non-null     object
 34  team               28 non-null     object
dtypes: float64(8), int64(21), object(6)
memory usage: 7.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 34 non-null     float64
 1   Player             35 non-null     object
 2   Age                34 non-null     float64
 3   Pos                33 non-null     object
 4   WAR                34 non-null     float64
 5   G                  35 non-null     int64
 6   PA                 35 non-null     int64
 7   AB                 35 non-null     int64
 8   R                  35 non-null     int64
 9   H▼                 35 non-null     int64
 10  2B                 35 non-null     int64
 11  3B                 35 non-null     int64
 12  HR                 35 non-null     int64
 13  RBI                35 non-null     int64
 14  SB                 35 non-null     int64
 15  CS                 35 non-null     int64
 16  BB                 35 non-null     int64
 17  SO                 35 non-null     int64
 18  BA                 28 non-null     float64
 19  OBP                28 non-null     float64
 20  SLG                28 non-null     float64
 21  OPS                28 non-null     float64
 22  OPS+               28 non-null     float64
 23  rOBA               28 non-null     float64
 24  Rbat+              28 non-null     float64
 25  TB                 35 non-null     int64
 26  GIDP               35 non-null     int64
 27  HBP                35 non-null     int64
 28  SH                 35 non-null     int64
 29  SF                 35 non-null     int64
 30  IBB                35 non-null     int64
 31  Pos.1              34 non-null     object
 32  Awards             5 non-null      object
 33  Player-additional  35 non-null     object
 34  team               35 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 9.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 33 non-null     float64
 1   Player             34 non-null     object
 2   Age                33 non-null     float64
 3   Pos                33 non-null     object
 4   WAR                34 non-null     float64
 5   G                  34 non-null     int64
 6   PA                 34 non-null     int64
 7   AB                 34 non-null     int64
 8   R                  34 non-null     int64
 9   H                  34 non-null     int64
 10  2B                 34 non-null     int64
 11  3B                 34 non-null     int64
 12  HR                 34 non-null     int64
 13  RBI                34 non-null     int64
 14  SB                 34 non-null     int64
 15  CS                 34 non-null     int64
 16  BB                 34 non-null     int64
 17  SO                 34 non-null     int64
 18  BA                 26 non-null     float64
 19  OBP                26 non-null     float64
 20  SLG                26 non-null     float64
 21  OPS                26 non-null     float64
 22  OPS+               26 non-null     float64
 23  rOBA               26 non-null     float64
 24  Rbat+              26 non-null     float64
 25  TB                 34 non-null     int64
 26  GIDP               34 non-null     int64
 27  HBP                34 non-null     int64
 28  SH                 34 non-null     int64
 29  SF                 34 non-null     int64
 30  IBB                34 non-null     int64
 31  Pos.1              33 non-null     object
 32  Awards             3 non-null      object
 33  Player-additional  34 non-null     object
 34  team               34 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 9.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 26 non-null     float64
 1   Player             27 non-null     object
 2   Age                26 non-null     float64
 3   Pos                26 non-null     object
 4   WAR                27 non-null     float64
 5   G                  27 non-null     int64
 6   PA                 27 non-null     int64
 7   AB                 27 non-null     int64
 8   R                  27 non-null     int64
 9   H                  27 non-null     int64
 10  2B                 27 non-null     int64
 11  3B                 27 non-null     int64
 12  HR                 27 non-null     int64
 13  RBI                27 non-null     int64
 14  SB                 27 non-null     int64
 15  CS                 27 non-null     int64
 16  BB                 27 non-null     int64
 17  SO                 27 non-null     int64
 18  BA                 24 non-null     float64
 19  OBP                24 non-null     float64
 20  SLG                24 non-null     float64
 21  OPS                24 non-null     float64
 22  OPS+               24 non-null     float64
 23  rOBA               24 non-null     float64
 24  Rbat+              24 non-null     float64
 25  TB                 27 non-null     int64
 26  GIDP               27 non-null     int64
 27  HBP                27 non-null     int64
 28  SH                 27 non-null     int64
 29  SF                 27 non-null     int64
 30  IBB                27 non-null     int64
 31  Pos.1              26 non-null     object
 32  Awards             2 non-null      object
 33  Player-additional  27 non-null     object
 34  team               27 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 7.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 31 non-null     float64
 1   Player             32 non-null     object
 2   Age                31 non-null     float64
 3   Pos                31 non-null     object
 4   WAR                32 non-null     float64
 5   G                  32 non-null     int64
 6   PA                 32 non-null     int64
 7   AB                 32 non-null     int64
 8   R                  32 non-null     int64
 9   H                  32 non-null     int64
 10  2B                 32 non-null     int64
 11  3B                 32 non-null     int64
 12  HR                 32 non-null     int64
 13  RBI                32 non-null     int64
 14  SB                 32 non-null     int64
 15  CS                 32 non-null     int64
 16  BB                 32 non-null     int64
 17  SO                 32 non-null     int64
 18  BA                 30 non-null     float64
 19  OBP                30 non-null     float64
 20  SLG                30 non-null     float64
 21  OPS                30 non-null     float64
 22  OPS+               30 non-null     float64
 23  rOBA               30 non-null     float64
 24  Rbat+              30 non-null     float64
 25  TB                 32 non-null     int64
 26  GIDP               32 non-null     int64
 27  HBP                32 non-null     int64
 28  SH                 32 non-null     int64
 29  SF                 32 non-null     int64
 30  IBB                32 non-null     int64
 31  Pos.1              31 non-null     object
 32  Awards             0 non-null      float64
 33  Player-additional  32 non-null     object
 34  team               32 non-null     object
dtypes: float64(11), int64(19), object(5)
memory usage: 8.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 36 non-null     float64
 1   Player             37 non-null     object
 2   Age                36 non-null     float64
 3   Pos                35 non-null     object
 4   WAR                36 non-null     float64
 5   G                  37 non-null     int64
 6   PA                 37 non-null     int64
 7   AB                 37 non-null     int64
 8   R                  37 non-null     int64
 9   H                  37 non-null     int64
 10  2B                 37 non-null     int64
 11  3B                 37 non-null     int64
 12  HR                 37 non-null     int64
 13  RBI                37 non-null     int64
 14  SB                 37 non-null     int64
 15  CS                 37 non-null     int64
 16  BB                 37 non-null     int64
 17  SO                 37 non-null     int64
 18  BA                 30 non-null     float64
 19  OBP                31 non-null     float64
 20  SLG                30 non-null     float64
 21  OPS                30 non-null     float64
 22  OPS+               30 non-null     float64
 23  rOBA               31 non-null     float64
 24  Rbat+              31 non-null     float64
 25  TB                 37 non-null     int64
 26  GIDP               37 non-null     int64
 27  HBP                37 non-null     int64
 28  SH                 37 non-null     int64
 29  SF                 37 non-null     int64
 30  IBB                37 non-null     int64
 31  Pos.1              36 non-null     object
 32  Awards             1 non-null      object
 33  Player-additional  37 non-null     object
 34  team               37 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 10.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 24 non-null     float64
 1   Player             25 non-null     object
 2   Age                24 non-null     float64
 3   Pos                24 non-null     object
 4   WAR                25 non-null     float64
 5   G                  25 non-null     int64
 6   PA                 25 non-null     int64
 7   AB                 25 non-null     int64
 8   R                  25 non-null     int64
 9   H                  25 non-null     int64
 10  2B                 25 non-null     int64
 11  3B                 25 non-null     int64
 12  HR                 25 non-null     int64
 13  RBI                25 non-null     int64
 14  SB                 25 non-null     int64
 15  CS                 25 non-null     int64
 16  BB                 25 non-null     int64
 17  SO                 25 non-null     int64
 18  BA                 22 non-null     float64
 19  OBP                22 non-null     float64
 20  SLG                22 non-null     float64
 21  OPS                22 non-null     float64
 22  OPS+               22 non-null     float64
 23  rOBA               22 non-null     float64
 24  Rbat+              22 non-null     float64
 25  TB                 25 non-null     int64
 26  GIDP               25 non-null     int64
 27  HBP                25 non-null     int64
 28  SH                 25 non-null     int64
 29  SF                 25 non-null     int64
 30  IBB                25 non-null     int64
 31  Pos.1              24 non-null     object
 32  Awards             5 non-null      object
 33  Player-additional  25 non-null     object
 34  team               25 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 7.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 31 non-null     float64
 1   Player             32 non-null     object
 2   Age                31 non-null     float64
 3   Pos                31 non-null     object
 4   WAR                32 non-null     float64
 5   G                  32 non-null     int64
 6   PA                 32 non-null     int64
 7   AB                 32 non-null     int64
 8   R                  32 non-null     int64
 9   H                  32 non-null     int64
 10  2B                 32 non-null     int64
 11  3B                 32 non-null     int64
 12  HR                 32 non-null     int64
 13  RBI                32 non-null     int64
 14  SB                 32 non-null     int64
 15  CS                 32 non-null     int64
 16  BB                 32 non-null     int64
 17  SO                 32 non-null     int64
 18  BA                 22 non-null     float64
 19  OBP                22 non-null     float64
 20  SLG                22 non-null     float64
 21  OPS                22 non-null     float64
 22  OPS+               22 non-null     float64
 23  rOBA               22 non-null     float64
 24  Rbat+              22 non-null     float64
 25  TB                 32 non-null     int64
 26  GIDP               32 non-null     int64
 27  HBP                32 non-null     int64
 28  SH                 32 non-null     int64
 29  SF                 32 non-null     int64
 30  IBB                32 non-null     int64
 31  Pos.1              31 non-null     object
 32  Awards             3 non-null      object
 33  Player-additional  32 non-null     object
 34  team               32 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 8.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 25 non-null     float64
 1   Player             26 non-null     object
 2   Age                25 non-null     float64
 3   Pos                25 non-null     object
 4   WAR                26 non-null     float64
 5   G                  26 non-null     int64
 6   PA                 26 non-null     int64
 7   AB                 26 non-null     int64
 8   R                  26 non-null     int64
 9   H                  26 non-null     int64
 10  2B                 26 non-null     int64
 11  3B                 26 non-null     int64
 12  HR                 26 non-null     int64
 13  RBI                26 non-null     int64
 14  SB                 26 non-null     int64
 15  CS                 26 non-null     int64
 16  BB                 26 non-null     int64
 17  SO                 26 non-null     int64
 18  BA                 24 non-null     float64
 19  OBP                24 non-null     float64
 20  SLG                24 non-null     float64
 21  OPS                24 non-null     float64
 22  OPS+               24 non-null     float64
 23  rOBA               24 non-null     float64
 24  Rbat+              24 non-null     float64
 25  TB                 26 non-null     int64
 26  GIDP               26 non-null     int64
 27  HBP                26 non-null     int64
 28  SH                 26 non-null     int64
 29  SF                 26 non-null     int64
 30  IBB                26 non-null     int64
 31  Pos.1              25 non-null     object
 32  Awards             1 non-null      object
 33  Player-additional  26 non-null     object
 34  team               26 non-null     object
dtypes: float64(10), int64(19), object(6)
memory usage: 7.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 27 non-null     float64
 1   Player             28 non-null     object
 2   Age                27 non-null     float64
 3   Pos                27 non-null     object
 4   WAR                28 non-null     float64
 5   G                  28 non-null     int64
 6   PA                 28 non-null     int64
 7   AB                 28 non-null     int64
 8   R                  28 non-null     int64
 9   H                  28 non-null     int64
 10  2B                 28 non-null     int64
 11  3B                 28 non-null     int64
 12  HR                 28 non-null     int64
 13  RBI                28 non-null     int64
 14  SB                 28 non-null     int64
 15  CS                 28 non-null     int64
 16  BB                 28 non-null     int64

In [65]:
dataframes['braves'].head()

,Rk,Player,Age,Pos,WAR,G,PA,AB,R,H,...,TB,GIDP,HBP,SH,SF,IBB,Pos.1,Awards,Player-additional,team
0,1.0,Travis d'Arnaud,35.0,C,1.1,99,341,307,40,73,...,134,8,6,0,4,0,2H,NaN,darnatr01,braves
1,2.0,Matt Olson*,30.0,1B,3.8,162,685,600,78,148,...,274,15,9,0,5,5,*3,NaN,olsonma02,braves
2,3.0,Ozzie Albies#,27.0,2B,1.6,99,435,399,52,100,...,161,6,5,0,4,0,4,NaN,albieoz01,braves
3,4.0,Orlando Arcia,29.0,SS,0.5,157,602,551,50,120,...,195,16,2,1,7,1,*6,NaN,arciaor01,braves
4,5.0,Austin Riley,27.0,3B,2.9,110,469,425,63,109,...,196,6,5,0,2,0,*5,NaN,rileyau01,braves

In [66]:
df = pd.concat(dataframes, ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Rk                 819 non-null    float64
 1   Player             849 non-null    object
 2   Age                819 non-null    float64
 3   Pos                817 non-null    object
 4   WAR                847 non-null    float64
 5   G                  849 non-null    float64
 6   PA                 849 non-null    float64
 7   AB                 849 non-null    float64
 8   R                  849 non-null    float64
 9   H                  814 non-null    float64
 10  2B                 849 non-null    float64
 11  3B                 849 non-null    float64
 12  HR                 849 non-null    float64
 13  RBI                849 non-null    float64
 14  SB                 849 non-null    float64
 15  CS                 849 non-null    float64
 16  BB                 849 non-null    float64
 17  SO                 849 non-null    float64
 18  BA                 756 non-null    float64
 19  OBP                757 non-null    float64
 20  SLG                756 non-null    float64
 21  OPS                756 non-null    float64
 22  OPS+               756 non-null    float64
 23  rOBA               757 non-null    float64
 24  Rbat+              757 non-null    float64
 25  TB                 849 non-null    float64
 26  GIDP               849 non-null    float64
 27  HBP                849 non-null    float64
 28  SH                 849 non-null    float64
 29  SF                 849 non-null    float64
 30  IBB                849 non-null    float64
 31  Pos.1              819 non-null    object
 32  Awards             77 non-null     object
 33  Player-additional  850 non-null    object
 34  team               850 non-null    object
 35  H▼                 35 non-null     float64
dtypes: float64(30), object(6)
memory usage: 239.2+ KB

In [67]:
df.dropna(subset=['Player'], inplace= True)
df['Player'].info()

<class 'pandas.core.series.Series'>
Index: 849 entries, 1 to 849
Series name: Player
Non-Null Count  Dtype
--------------  -----
849 non-null    object
dtypes: object(1)
memory usage: 13.3+ KB

In [68]:
df = df.drop(columns=['Rk','H▼','Player-additional', 'Pos.1']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 849 entries, 1 to 849
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  849 non-null    object
 1   Age     819 non-null    float64
 2   Pos     817 non-null    object
 3   WAR     847 non-null    float64
 4   G       849 non-null    float64
 5   PA      849 non-null    float64
 6   AB      849 non-null    float64
 7   R       849 non-null    float64
 8   H       814 non-null    float64
 9   2B      849 non-null    float64
 10  3B      849 non-null    float64
 11  HR      849 non-null    float64
 12  RBI     849 non-null    float64
 13  SB      849 non-null    float64
 14  CS      849 non-null    float64
 15  BB      849 non-null    float64
 16  SO      849 non-null    float64
 17  BA      756 non-null    float64
 18  OBP     757 non-null    float64
 19  SLG     756 non-null    float64
 20  OPS     756 non-null    float64
 21  OPS+    756 non-null    float64
 22  rOBA    757 non-null    float64
 23  Rbat+   757 non-null    float64
 24  TB      849 non-null    float64
 25  GIDP    849 non-null    float64
 26  HBP     849 non-null    float64
 27  SH      849 non-null    float64
 28  SF      849 non-null    float64
 29  IBB     849 non-null    float64
 30  Awards  77 non-null     object
 31  team    849 non-null    object
dtypes: float64(28), object(4)
memory usage: 218.9+ KB

In [69]:
df['Last_Char'] = df['Player'].str[-1]
df['dominant_hand'] = ''  

for idx, row in df.iterrows(): 
    if row['Last_Char'] == '*':    
        df.loc[idx, 'dominant_hand'] = 'Left'
    elif row['Last_Char'] == '#':
        df.loc[idx, 'dominant_hand'] = 'Both'
    elif row['Last_Char'] == '?':
        df.loc[idx, 'dominant_hand'] = 'Unknown'
    else:
        df.loc[idx, 'dominant_hand'] = 'Right'

In [70]:
df.tail()

,Player,Age,Pos,WAR,G,PA,AB,R,H,2B,...,TB,GIDP,HBP,SH,SF,IBB,Awards,team,Last_Char,dominant_hand
845,Darren Baker*,25.0,UT,0.0,9.0,14.0,14.0,1.0,7.0,2.0,...,9.0,0.0,0.0,0.0,0.0,0.0,NaN,nationals,*,Left
846,Stone Garrett,28.0,DH,0.3,2.0,6.0,5.0,2.0,3.0,1.0,...,7.0,0.0,0.0,0.0,0.0,0.0,NaN,nationals,t,Right
847,Derek Law,33.0,P,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,nationals,w,Right
848,Kyle Finnegan,32.0,P,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,AS,nationals,n,Right
849,Team Totals,NaN,NaN,13.7,162.0,5971.0,5374.0,660.0,1306.0,267.0,...,2014.0,115.0,73.0,26.0,40.0,11.0,NaN,nationals,s,Right

In [71]:
# Remove suffix characters from Players column
for idx, row in df.iterrows():
    if row['Last_Char'] in ['*', '#', '?']:
        df.loc[idx, 'Player'] = row['Player'][:-1]

df["Player"].head(10)

1          Gabriel Moreno
2        Christian Walker
3             Ketel Marte
4         Geraldo Perdomo
5          Eugenio Suárez
6     Lourdes Gurriel Jr.
7          Corbin Carroll
8           Jake McCarthy
9            Joc Pederson
10           Kevin Newman
Name: Player, dtype: object

In [72]:
df = df.drop(columns=['Last_Char']) 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 849 entries, 1 to 849
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         849 non-null    object
 1   Age            819 non-null    float64
 2   Pos            817 non-null    object
 3   WAR            847 non-null    float64
 4   G              849 non-null    float64
 5   PA             849 non-null    float64
 6   AB             849 non-null    float64
 7   R              849 non-null    float64
 8   H              814 non-null    float64
 9   2B             849 non-null    float64
 10  3B             849 non-null    float64
 11  HR             849 non-null    float64
 12  RBI            849 non-null    float64
 13  SB             849 non-null    float64
 14  CS             849 non-null    float64
 15  BB             849 non-null    float64
 16  SO             849 non-null    float64
 17  BA             756 non-null    float64
 18  OBP            757 non-null    float64
 19  SLG            756 non-null    float64
 20  OPS            756 non-null    float64
 21  OPS+           756 non-null    float64
 22  rOBA           757 non-null    float64
 23  Rbat+          757 non-null    float64
 24  TB             849 non-null    float64
 25  GIDP           849 non-null    float64
 26  HBP            849 non-null    float64
 27  SH             849 non-null    float64
 28  SF             849 non-null    float64
 29  IBB            849 non-null    float64
 30  Awards         77 non-null     object
 31  team           849 non-null    object
 32  dominant_hand  849 non-null    object
dtypes: float64(28), object(5)
memory usage: 257.8+ KB

In [73]:
df = df[['Player', 'team', 'Age', 'Pos', 'dominant_hand','G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS','BB', 'SO', 'HBP', 'TB', 'GIDP', 'SH', 'SF', 'IBB','BA', 'OBP', 'SLG', 'OPS','OPS+', 'rOBA', 'Rbat+', 'WAR','Awards']]
df.head()

,Player,team,Age,Pos,dominant_hand,G,PA,AB,R,H,...,IBB,BA,OBP,SLG,OPS,OPS+,rOBA,Rbat+,WAR,Awards
1,Gabriel Moreno,diamondbacks,24.0,C,Right,97.0,351.0,305.0,39.0,81.0,...,1.0,0.266,0.353,0.380,0.734,104.0,0.327,105.0,2.6,NaN
2,Christian Walker,diamondbacks,33.0,1B,Right,130.0,552.0,479.0,72.0,120.0,...,4.0,0.251,0.335,0.468,0.803,120.0,0.340,116.0,2.6,GG
3,Ketel Marte,diamondbacks,30.0,2B,Both,136.0,583.0,504.0,93.0,147.0,...,7.0,0.292,0.372,0.560,0.932,154.0,0.396,155.0,6.8,ASMVP-3SS
4,Geraldo Perdomo,diamondbacks,24.0,SS,Both,98.0,388.0,337.0,61.0,92.0,...,0.0,0.273,0.344,0.374,0.718,100.0,0.328,104.0,3.5,NaN
5,Eugenio Suárez,diamondbacks,32.0,3B,Right,158.0,640.0,571.0,90.0,146.0,...,0.0,0.256,0.319,0.469,0.788,115.0,0.340,115.0,3.1,NaN

In [74]:
df.to_csv('api_teams_data.csv', index=False)

In [75]:
df.columns

Index(['Player', 'team', 'Age', 'Pos', 'dominant_hand', 'G', 'PA', 'AB', 'R',
       'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'HBP', 'TB',
       'GIDP', 'SH', 'SF', 'IBB', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'rOBA',
       'Rbat+', 'WAR', 'Awards'],
      dtype='object')

In [76]:
df['Pos'].value_counts()

Pos
C     97
P     91
OF    75
3B    66
RF    58
1B    58
DH    56
2B    54
CF    51
IF    50
LF    47
SS    46
UT    44
MI    12
CI    12
Name: count, dtype: int64